def get_remote_startup_command(
    port: int,
    sandbox_workspace_dir: str,
    username: str,
    user_id: int,
    plugin_args: list[str],
    browsergym_args: list[str],
):
    return [
        '/omninexus/micromamba/bin/micromamba',
        'run',
        '-n',
        'omninexus',
        'poetry',
        'run',
        'python',
        '-u',
        '-m',
        'omninexus.runtime.action_execution_server',
        str(port),
        '--working-dir',
        sandbox_workspace_dir,
        *plugin_args,
        '--username',
        username,
        '--user-id',
        str(user_id),
        *browsergym_args,
    ]
